services:
  db:
    image: postgres:16-alpine
    restart: always
    user: postgres
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/POSTGRES_PASSWORD
    secrets:
      - POSTGRES_PASSWORD
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:

secrets:
  POSTGRES_PASSWORD:
    environment: POSTGRES_PASSWORD
