services:

  api_server:
    restart: on-failure
    build:
      args:
        PACKAGE: api_server
        PROFILE: dev
    ports:
      - 3000:3000/tcp
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild

  file_server:
    restart: on-failure
    build:
      args:
        PACKAGE: file_server
        PROFILE: dev
    ports:
      - 3001:3001/tcp
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild

  db:
    image: postgres:16-alpine
    restart: on-failure
    user: postgres
    expose:
      - 5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/POSTGRES_PASSWORD
    secrets:
      - POSTGRES_PASSWORD
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:

secrets:
  POSTGRES_PASSWORD:
    environment: POSTGRES_PASSWORD
