services:

  file_server:
    build:
      args:
        BIN_NAME: file_server
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy

  api_server:
    build:
      args:
        BIN_NAME: api_server
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    restart: on-failure
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    secrets:
      - db-password
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:

secrets:
  db-password:
    environment: DB_PASSWORD
