[build]
rustflags = [
    # Enables performance optimizations specific to the CPU being compiled on.
    # We don't distribute cross-platform binaries, so this has no downside.
    "-Ctarget-cpu=native",
]
