[build]
rustflags = [
    # Enables performance optimizations specific to the CPU being compiled on.
    # We don't distribute cross-platform binaries, so this has no downside.
    "-Ctarget-cpu=native",

    # ==== Lints ====
    # Last updated for Clippy version: 1.85

    # Enforces soundness.
    "-Dunsafe_code",

    # Enforces documentation.
    "-Wclippy::allow_attributes_without_reason",
    "-Wclippy::missing_docs_in_private_items",
    "-Wclippy::missing_errors_doc",
    "-Wmissing_docs",

    # Enforces panics are explicit and justified.
    "-Wclippy::assertions_on_result_states",
    "-Wclippy::missing_assert_message",
    "-Wclippy::unchecked_duration_subtraction",
    "-Wclippy::unwrap_used",

    # Helps performance and memory usage.
    "-Wclippy::trivially_copy_pass_by_ref",
    "-Wclippy::unnecessary_box_returns",
    "-Wclippy::unused_async",

    # Helps future-proofing and extensibility.
    "-Wclippy::allow_attributes",
    "-Wclippy::cast_lossless",
    "-Wclippy::cloned_instead_of_copied",
    "-Wclippy::empty_enum",
    "-Wclippy::enum_glob_use",
    "-Wclippy::future_not_send",
    "-Wclippy::impl_trait_in_params",
    "-Wclippy::implicit_hasher",
    "-Wclippy::into_iter_without_iter",
    "-Wclippy::iter_without_into_iter",
    "-Wclippy::needless_pass_by_ref_mut",
    "-Wclippy::needless_pass_by_value",
    "-Wclippy::partial_pub_fields",
    "-Wclippy::ref_option_ref",
    "-Wclippy::rest_pat_in_fully_bound_structs",
    "-Wclippy::semicolon_if_nothing_returned",
    "-Wclippy::should_panic_without_expect",
    "-Wmissing_debug_implementations",

    # Helps readability, clarity, and consistency.
    "-Wclippy::checked_conversions",
    "-Wclippy::clear_with_drain",
    "-Wclippy::clone_on_ref_ptr",
    "-Wclippy::copy_iterator",
    "-Wclippy::default_trait_access",
    "-Wclippy::empty_enum_variants_with_brackets",
    "-Wclippy::empty_line_after_doc_comments",
    "-Wclippy::empty_line_after_outer_attr",
    "-Wclippy::equatable_if_let",
    "-Wclippy::expl_impl_clone_on_copy",
    "-Wclippy::explicit_deref_methods",
    "-Wclippy::explicit_into_iter_loop",
    "-Wclippy::explicit_iter_loop",
    "-Wclippy::filter_map_next",
    "-Wclippy::flat_map_option",
    "-Wclippy::from_iter_instead_of_collect",
    "-Wclippy::if_not_else",
    "-Wclippy::if_then_some_else_none",
    "-Wclippy::implicit_clone",
    "-Wclippy::inconsistent_struct_constructor",
    "-Wclippy::iter_filter_is_ok",
    "-Wclippy::iter_filter_is_some",
    "-Wclippy::iter_not_returning_iterator",
    "-Wclippy::manual_assert",
    "-Wclippy::manual_c_str_literals",
    "-Wclippy::manual_clamp",
    "-Wclippy::manual_instant_elapsed",
    "-Wclippy::manual_is_variant_and",
    "-Wclippy::manual_let_else",
    "-Wclippy::manual_ok_or",
    "-Wclippy::match_bool",
    "-Wclippy::mixed_read_write_in_expression",
    "-Wclippy::mod_module_files",
    "-Wclippy::needless_bitwise_bool",
    "-Wclippy::needless_continue",
    "-Wclippy::needless_for_each",
    "-Wclippy::needless_raw_string_hashes",
    "-Wclippy::nonstandard_macro_braces",
    "-Wclippy::option_as_ref_cloned",
    "-Wclippy::option_option",
    "-Wclippy::pub_without_shorthand",
    "-Wclippy::range_minus_one",
    "-Wclippy::range_plus_one",
    "-Wclippy::redundant_clone",
    "-Wclippy::redundant_closure_for_method_calls",
    "-Wclippy::redundant_else",
    "-Wclippy::redundant_type_annotations",
    "-Wclippy::ref_binding_to_reference",
    "-Wclippy::semicolon_inside_block",
    "-Wclippy::single_match_else",
    "-Wclippy::string_add",
    "-Wclippy::string_add_assign",
    "-Wclippy::string_to_string",
    "-Wclippy::trait_duplication_in_bounds",
    "-Wclippy::try_err",
    "-Wclippy::type_repetition_in_bounds",
    "-Wclippy::uninlined_format_args",
    "-Wclippy::unnecessary_join",
    "-Wclippy::unnested_or_patterns",
    "-Wclippy::unseparated_literal_suffix",
    "-Wclippy::unused_result_ok",
    "-Wclippy::unused_self",
    "-Wclippy::use_self",
    "-Wclippy::used_underscore_binding",
    "-Wclippy::useless_let_if_seq",
    "-Wclippy::zero_sized_map_values",
    "-Wnon_ascii_idents",
    "-Wunreachable_pub",

    # Catches accidents.
    "-Wclippy::collection_is_never_read",
    "-Wclippy::dbg_macro",
    "-Wclippy::debug_assert_with_mut_call",
    "-Wclippy::doc_link_with_quotes",
    "-Wclippy::empty_drop",
    "-Wclippy::exit",
    "-Wclippy::float_cmp",
    "-Wclippy::fn_to_numeric_cast_any",
    "-Wclippy::infinite_loop",
    "-Wclippy::lossy_float_literal",
    "-Wclippy::mut_mut",
    "-Wclippy::rc_mutex",
    "-Wclippy::read_zero_byte_vec",
    "-Wclippy::readonly_write_lock",
    "-Wclippy::tests_outside_test_module",
    "-Wclippy::todo",
    "-Wclippy::unimplemented",
    "-Wclippy::unnecessary_safety_comment",
    "-Wclippy::unnecessary_safety_doc",
    "-Wclippy::unnecessary_self_imports",
    "-Wclippy::unreachable",
    "-Wclippy::unused_rounding",
    "-Wrustdoc::unescaped_backticks",
    "-Wunused_crate_dependencies",

    # Helps accuracy and precision.
    "-Wclippy::imprecise_flops",
    "-Wclippy::suboptimal_flops",
]
