[package]
name = "file_server"
version = "0.1.0"
edition = "2021"
publish = false

[lints]
workspace = true

[dependencies]
axum = { version = "0.7" }
axum-macros = "0.4"
tokio = { version = "1", features = ["full"] }
