[package]
name = "file_server"
version = "0.1.0"
edition = "2021"
publish = false

[lints]
workspace = true

[dependencies]
axum = "0.7"
axum-macros = "0.4"
percent-encoding = "2"
tokio = { version = "1", features = ["full"] }
